version: "3.3"

services:
  mcp-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-manager
    restart: unless-stopped
    ports:
      - "2005:2005"
    networks:
      - proxy-net
    environment:
      - TZ=Asia/Jakarta

networks:
  proxy-net:
    external: true
